### ISSUE TITLE
Should stimulation_wavelength of LightSource match the excitation_lambda of PatternedOptogeneticStimulusSite?

### ISSUE THREAD

**Issue by CodyCBakerPhD** [catalystneuro/ndx-patterned-ogen#11]
@alessandratrapani Should the `stimulation_wavelength` of a `LightSource` always match the `excitation_lambda` of a `PatternedOptogeneticStimulusSite`?

I know the latter inherits the field from its parent - is there any way to exclude that, or is removing that field  simply a 'to-do' item when these are integrated into core?

If so, do we have a list started somewhere highlighting all the changes we would make it the inheritance were refactored at the higher levels (similar to ndx-microscopy)?

**Comment by alessandratrapani** [comment]
> Should the stimulation_wavelength of a LightSource always match the excitation_lambda of a PatternedOptogeneticStimulusSite?

Yes

> I know the latter inherits the field from its parent - is there any way to exclude that, or is removing that field simply a 'to-do' item when these are integrated into core?

Yes, similarly to ndx-microscopy. Note that LightSource will be a  neurodatatype shared by ndx-microscopy and ndx-patterned-ogen. 

> If so, do we have a list started somewhere highlighting all the changes we would make it the inheritance were refactored at the higher levels (similar to ndx-microscopy)?

Good point, I opened an issue here specifically for this: #12
